[workspace]
members = [
    "libbzip2-rs-sys",
    "test-libbzip2-rs-sys",
]
package.edition = "2021"


[package]
name = "c2rust_out"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.82" # MSRV

[[bin]]
name = "bzip2"
path = "bzip2.rs"

[[bin]]
name = "bzip2recover"
path = "bzip2recover.rs"

[workspace.dependencies]
libc = "0.2"
libbzip2-rs-sys = { path = "libbzip2-rs-sys/", default-features = false }


[dependencies]
libc = "0.2"
libbzip2-rs-sys = { path = "libbzip2-rs-sys/", default-features = false }

[dev-dependencies]
tempfile = "3.13.0"
crc32fast = "=1.4.2"
